server:
  port: 8000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**

        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**

        - id: ITEM-SERVICE
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/items/**

        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/registration/**, /sign_in/**, /users/**

        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true