server:
  port: 8085
  servlet:
    session:
      cookie:
        http-only: false
        secure: false

spring:
  application:
    name: CART-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/cart_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: localhost
    password: mypassword
    port: 6379
    username:

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

    timeout: 300

  config:
    import: optional:configserver:http://localhost:8086
