spring:
  application:
    name: CATEGORY-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/category_service
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  config:
    import: optional:configserver:http://localhost:8086

server:
  port: 8090